# Generated by Django 3.2.5 on 2022-04-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=1000)),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('book_cover', models.ImageField(upload_to='photos/')),
                ('categories', models.CharField(choices=[('Comic', 'Comic'), ('Fantasy', 'Fantasy'), ('Action', 'Action'), ('Thriller', 'Thriller'), ('Contemporary', 'Contemporary')], max_length=20)),
                ('archived', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['archived'],
            },
        ),
    ]
